/**
 * formatter.ts — serialises ContentBlock[] into a printable HTML string.
 *
 * The HTML is self-contained (inline styles only, no external CSS) so it
 * renders correctly in any browser for print or PDF export — important for
 * rural schools with limited internet access that may print lesson plans.
 *
 * Also exports serializeToJson() for API consumers that prefer structured data.
 */

import type { ContentBlock, LessonPlan } from "@/types/entities";

/**
 * Produce a print-ready HTML string from a set of ContentBlocks.
 * Designed for A4 paper. No JavaScript — purely declarative HTML + inline CSS.
 */
export function formatToPrintableHtml(
  plan: Pick<LessonPlan, "subjectId" | "topicId" | "weekOf" | "curriculumStandard">,
  contentBlocks: ContentBlock[]
): string {
  const levelLabels: Record<string, string> = {
    remedial: "🟡 Remedial — Foundational Support",
    on_track: "🟢 On Track — Standard Level",
    advanced: "🔵 Advanced — Enrichment",
  };

  const blockHtml = contentBlocks
    .map(
      (b) => `
    <section style="margin-bottom:32px;page-break-inside:avoid;">
      <h2 style="font-size:16px;font-weight:bold;border-left:4px solid #2563eb;padding-left:10px;margin-bottom:8px;">
        ${levelLabels[b.level] ?? b.level} — ${escHtml(b.title)}
      </h2>
      <p style="font-size:13px;line-height:1.7;margin-bottom:12px;">
        <strong>Explanation:</strong> ${escHtml(b.explanation)}
      </p>
      <div style="background:#f0f9ff;padding:12px;border-radius:6px;margin-bottom:12px;">
        <strong style="font-size:13px;">Classroom Activity (≈${b.estimatedMinutes} min):</strong>
        <p style="font-size:13px;line-height:1.6;margin-top:4px;">${escHtml(b.activity)}</p>
      </div>
      <div style="background:#fafafa;padding:12px;border-radius:6px;border:1px solid #e5e7eb;">
        <strong style="font-size:13px;">Worksheet / Practice:</strong>
        <pre style="font-size:13px;line-height:1.7;margin-top:4px;white-space:pre-wrap;font-family:inherit;">${escHtml(b.worksheet)}</pre>
      </div>
    </section>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Lesson Plan — ${escHtml(plan.subjectId)} — ${escHtml(plan.topicId)}</title>
  <style>
    @media print { body { margin: 0; } .no-print { display: none; } }
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1f2328; }
  </style>
</head>
<body>
  <header style="border-bottom:2px solid #2563eb;padding-bottom:12px;margin-bottom:24px;">
    <h1 style="font-size:20px;font-weight:bold;margin:0 0 4px;">
      Lesson Plan — ${escHtml(plan.subjectId)}: ${escHtml(plan.topicId)}
    </h1>
    <p style="font-size:13px;color:#57606a;margin:0;">
      Week of ${escHtml(plan.weekOf)} &nbsp;|&nbsp; ${escHtml(plan.curriculumStandard ?? "NCERT Class 6")}
    </p>
  </header>
  ${blockHtml}
  <footer style="margin-top:40px;border-top:1px solid #e5e7eb;padding-top:12px;font-size:11px;color:#57606a;text-align:center;">
    Generated by Setu — AI Personalized Learning Platform
  </footer>
</body>
</html>`;
}

/** Minimal HTML entity escaping to prevent XSS in generated content */
function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Serialise ContentBlocks to a structured JSON string (for API consumers) */
export function serializeToJson(contentBlocks: ContentBlock[]): string {
  return JSON.stringify({ contentBlocks }, null, 2);
}
